@startuml
class Curve{
	-x : tenor
	-y : yields
	+set_curve(x,y)
	+interpolate(method,new_tenor)
}

class TsyYldCurve{
	+__call__()
	+getForwardCurve()
}

class ForwardCurve{
	+__call__()
	+generateSpotCurve()
}

class SpotRateCurve{
	+__call__()
	+generateForwardCurve()
}

TsyYldCurve -up--|> Curve
SpotRateCurve -up--|> Curve
ForwardCurve -up--|> Curve


class IRModels{
	-spotRates : pd.DataFrame
	+DF(tenor)
}

class Vasicek{
	-args
	+__call__(opt,method)
	+clalibarte()
	+nanalytic()
	+MC()
}

class BDT{
	-args
	+__call__(opt,method)
	+clalibarte()
	+tree()
}

class HullWhite{
	-args
	+__call__(opt,method)
	+clalibarte()
	+tree()
}

IRModels <|-- HullWhite
IRModels <|-- Vasicek
IRModels <|-- BDT

class BondOptionPricer{
	-opt
	-spot
	-step
	-model
	+spotBootstrapping()
	+volStructure()
	+calibrateIRModel()
	+getOptionPrice()
}

BondOptionPricer o-- IRModels
Curve -right--o IRModels


@enduml